// This is our last exercise. Let's go down a more unstructured path!
// Try writing an **asynchronous REST API** to expose the functionality
// of the ticket management system we built throughout the course.
// It should expose endpoints to:
//  - Create a ticket
//  - Retrieve ticket details
//  - Patch a ticket
//
// Use Rust's package registry, crates.io, to find the dependencies you need
// (if any) to build this system.

/* BELOW SOLUTION GENERATED BY CODEX, NOT TESTED */



// - Hooked up an Axum-based entry point with serve, app, and router wiring so POST/GET/PATCH routes all share the same asynchronous TicketStore built on Arc<RwLock<BTreeMap<…>>>, giving us a simple in-memory backend for the REST API (lib.rs (line 31), lib.rs (line 41), lib.rs (line 71)).
// - Added the ticket domain model—Ticket, TicketId, strongly-typed Status with custom serde/display impls, plus validation-powered TicketDraft/TicketPatch builders and error plumbing—so requests are consistently normalized and bad inputs are surfaced with structured JSON errors (lib.rs (line 114), lib.rs (line 187), lib.rs (line 232), lib.rs (line 302)).
// - Implemented the HTTP handlers for create/get/patch to convert payloads, hit the store, and emit the right status codes/responses, then documented the behavior with two integration-style tests that exercise the ticket lifecycle via the router (lib.rs (line 331), lib.rs (line 340), lib.rs (line 350), lib.rs (line 374)).
// - Brought in the async HTTP stack and testing utilities (Axum, Hyper, Serde, ThisError, Tower, http-body-util) so the crate can compile and the router can be driven directly in tests (Cargo.toml (line 6)).

// Tests: cargo test -p outro_08.

// Next steps (optional):
// - add listing/deletion endpoints or persistence if you want parity with a real ticket service;
// - wire the serve function into a binary that binds to a socket so it’s easy to run the API outside of tests.



use std::collections::BTreeMap;
use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use serde::{Deserialize, Serialize};
use serde_json::json;
use thiserror::Error;
use tokio::net::TcpListener;
use tokio::sync::RwLock;

/// Launch the REST API server on the provided listener.
pub async fn serve(listener: TcpListener) -> Result<(), std::io::Error> {
    axum::serve(listener, app()).await
}

/// Build the router so that tests (or binaries) can run it with a custom listener.
pub fn app() -> Router {
    app_with_state(ApiState::default())
}

fn app_with_state(state: ApiState) -> Router {
    Router::new()
        .route("/tickets", post(create_ticket))
        .route("/tickets/:id", get(get_ticket).patch(patch_ticket))
        .with_state(state)
}

#[derive(Clone)]
struct ApiState {
    store: TicketStore,
}

impl Default for ApiState {
    fn default() -> Self {
        Self {
            store: TicketStore::new(),
        }
    }
}

#[derive(Clone)]
struct TicketStore {
    inner: Arc<InnerStore>,
}

struct InnerStore {
    tickets: RwLock<BTreeMap<TicketId, Ticket>>,
    next_id: AtomicU64,
}

impl TicketStore {
    fn new() -> Self {
        Self {
            inner: Arc::new(InnerStore {
                tickets: RwLock::new(BTreeMap::new()),
                next_id: AtomicU64::new(0),
            }),
        }
    }

    async fn create_ticket(&self, draft: TicketDraft) -> Ticket {
        let id = TicketId(self.inner.next_id.fetch_add(1, Ordering::SeqCst));
        let ticket = Ticket {
            id,
            title: draft.title,
            description: draft.description,
            status: Status::ToDo,
        };

        self.inner.tickets.write().await.insert(id, ticket.clone());
        ticket
    }

    async fn get_ticket(&self, id: TicketId) -> Option<Ticket> {
        self.inner.tickets.read().await.get(&id).cloned()
    }

    async fn patch_ticket(&self, id: TicketId, patch: TicketPatch) -> Option<Ticket> {
        let mut guard = self.inner.tickets.write().await;
        let ticket = guard.get_mut(&id)?;
        if let Some(title) = patch.title {
            ticket.title = title;
        }
        if let Some(description) = patch.description {
            ticket.description = description;
        }
        if let Some(status) = patch.status {
            ticket.status = status;
        }
        Some(ticket.clone())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Ticket {
    pub id: TicketId,
    pub title: String,
    pub description: String,
    pub status: Status,
}

#[derive(Debug, Clone)]
struct TicketDraft {
    title: String,
    description: String,
}

impl TicketDraft {
    fn new(title: String, description: String) -> Result<Self, ValidationError> {
        validate_title(&title)?;
        validate_description(&description)?;
        Ok(Self { title, description })
    }
}

#[derive(Debug, Clone)]
struct TicketPatch {
    title: Option<String>,
    description: Option<String>,
    status: Option<Status>,
}

impl TicketPatch {
    fn new(
        title: Option<String>,
        description: Option<String>,
        status: Option<Status>,
    ) -> Result<Self, ValidationError> {
        if let Some(title) = title.as_ref() {
            validate_title(title)?;
        }
        if let Some(description) = description.as_ref() {
            validate_description(description)?;
        }
        if title.is_none() && description.is_none() && status.is_none() {
            return Err(ValidationError::EmptyPatch);
        }
        Ok(Self {
            title,
            description,
            status,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct TicketId(u64);

impl From<u64> for TicketId {
    fn from(value: u64) -> Self {
        Self(value)
    }
}

impl From<TicketId> for u64 {
    fn from(value: TicketId) -> Self {
        value.0
    }
}

impl fmt::Display for TicketId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Status {
    ToDo,
    InProgress,
    Done,
}

impl Status {
    fn as_str(&self) -> &'static str {
        match self {
            Status::ToDo => "todo",
            Status::InProgress => "in_progress",
            Status::Done => "done",
        }
    }

    fn from_str(value: &str) -> Result<Self, ValidationError> {
        match value.to_lowercase().as_str() {
            "todo" => Ok(Status::ToDo),
            "in_progress" | "inprogress" => Ok(Status::InProgress),
            "done" => Ok(Status::Done),
            other => Err(ValidationError::InvalidStatus(other.to_string())),
        }
    }
}

impl Serialize for Status {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for Status {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Status::from_str(&value).map_err(serde::de::Error::custom)
    }
}

#[derive(Debug, Error)]
enum ValidationError {
    #[error("the title cannot be empty")]
    EmptyTitle,
    #[error("the title cannot be longer than 50 characters")]
    TitleTooLong,
    #[error("the description cannot be empty")]
    EmptyDescription,
    #[error("the description cannot be longer than 500 characters")]
    DescriptionTooLong,
    #[error("at least one field must be provided to patch a ticket")]
    EmptyPatch,
    #[error("{0} is not a valid status. Use todo, in_progress or done.")]
    InvalidStatus(String),
}

const TITLE_LIMIT: usize = 50;
const DESCRIPTION_LIMIT: usize = 500;

fn validate_title(title: &str) -> Result<(), ValidationError> {
    if title.trim().is_empty() {
        Err(ValidationError::EmptyTitle)
    } else if title.len() > TITLE_LIMIT {
        Err(ValidationError::TitleTooLong)
    } else {
        Ok(())
    }
}

fn validate_description(description: &str) -> Result<(), ValidationError> {
    if description.trim().is_empty() {
        Err(ValidationError::EmptyDescription)
    } else if description.len() > DESCRIPTION_LIMIT {
        Err(ValidationError::DescriptionTooLong)
    } else {
        Ok(())
    }
}

#[derive(Debug, Error)]
enum ApiError {
    #[error("{0}")]
    InvalidInput(String),
    #[error("ticket not found")]
    NotFound,
}

impl From<ValidationError> for ApiError {
    fn from(value: ValidationError) -> Self {
        ApiError::InvalidInput(value.to_string())
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        match self {
            ApiError::InvalidInput(message) => (
                StatusCode::UNPROCESSABLE_ENTITY,
                Json(json!({ "error": message })),
            )
                .into_response(),
            ApiError::NotFound => (
                StatusCode::NOT_FOUND,
                Json(json!({ "error": "ticket not found" })),
            )
                .into_response(),
        }
    }
}

#[derive(Deserialize)]
struct CreateTicketRequest {
    title: String,
    description: String,
}

#[derive(Deserialize)]
struct PatchTicketRequest {
    title: Option<String>,
    description: Option<String>,
    status: Option<Status>,
}

impl TryFrom<CreateTicketRequest> for TicketDraft {
    type Error = ValidationError;

    fn try_from(value: CreateTicketRequest) -> Result<Self, Self::Error> {
        TicketDraft::new(value.title, value.description)
    }
}

impl TryFrom<PatchTicketRequest> for TicketPatch {
    type Error = ValidationError;

    fn try_from(value: PatchTicketRequest) -> Result<Self, Self::Error> {
        TicketPatch::new(value.title, value.description, value.status)
    }
}

async fn create_ticket(
    State(state): State<ApiState>,
    Json(payload): Json<CreateTicketRequest>,
) -> Result<impl IntoResponse, ApiError> {
    let draft = TicketDraft::try_from(payload)?;
    let ticket = state.store.create_ticket(draft).await;
    Ok((StatusCode::CREATED, Json(ticket)))
}

async fn get_ticket(
    State(state): State<ApiState>,
    Path(id): Path<u64>,
) -> Result<Json<Ticket>, ApiError> {
    match state.store.get_ticket(TicketId::from(id)).await {
        Some(ticket) => Ok(Json(ticket)),
        None => Err(ApiError::NotFound),
    }
}

async fn patch_ticket(
    State(state): State<ApiState>,
    Path(id): Path<u64>,
    Json(payload): Json<PatchTicketRequest>,
) -> Result<Json<Ticket>, ApiError> {
    let patch = TicketPatch::try_from(payload)?;
    match state
        .store
        .patch_ticket(TicketId::from(id), patch)
        .await
    {
        Some(ticket) => Ok(Json(ticket)),
        None => Err(ApiError::NotFound),
    }
}

#[cfg(test)]
mod tests {
    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use http_body_util::BodyExt;
    use serde_json::{json, Value};
    use tower::ServiceExt;

    #[tokio::test]
    async fn create_ticket_endpoint_returns_created_ticket() {
        let app = super::app();
        let payload = json!({
            "title": "Learn async Rust",
            "description": "Use Axum to expose the store"
        });

        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/tickets")
                    .header("content-type", "application/json")
                    .body(Body::from(payload.to_string()))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::CREATED);
        let body_bytes = response.into_body().collect().await.unwrap().to_bytes();
        let body: Value = serde_json::from_slice(&body_bytes).unwrap();
        assert_eq!(body["title"], "Learn async Rust");
        assert_eq!(body["description"], "Use Axum to expose the store");
        assert_eq!(body["status"], "todo");
        assert_eq!(body["id"], 0);
    }

    #[tokio::test]
    async fn ticket_lifecycle() {
        let app = super::app();

        // Create a ticket
        let create_response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/tickets")
                    .header("content-type", "application/json")
                    .body(
                        Body::from(
                            json!({"title": "Ship feature", "description": "Finish the API"}).to_string(),
                        ),
                    )
                    .unwrap(),
            )
            .await
            .unwrap();

        let body = create_response
            .into_body()
            .collect()
            .await
            .unwrap()
            .to_bytes();
        let created: Value = serde_json::from_slice(&body).unwrap();
        let id = created["id"].as_u64().unwrap();

        // Retrieve it
        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("GET")
                    .uri(format!("/tickets/{id}"))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);

        // Patch it
        let patch_response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("PATCH")
                    .uri(format!("/tickets/{id}"))
                    .header("content-type", "application/json")
                    .body(
                        Body::from(
                            json!({
                                "status": "done",
                                "description": "All done!"
                            })
                            .to_string(),
                        ),
                    )
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(patch_response.status(), StatusCode::OK);
        let body = patch_response
            .into_body()
            .collect()
            .await
            .unwrap()
            .to_bytes();
        let updated: Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(updated["status"], "done");
        assert_eq!(updated["description"], "All done!");
        assert_eq!(updated["id"].as_u64().unwrap(), id);

        // Unknown ticket yields 404
        let missing = app
            .oneshot(
                Request::builder()
                    .method("GET")
                    .uri("/tickets/999")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(missing.status(), StatusCode::NOT_FOUND);
    }
}
