CFLAGS=-Wall -g

# it means `all` depends on `clean` and `ex1`
all: clean ex1
		echo "done"

# always need indent
clean:
		rm -f ex1

# run `man make` to read doc about make command and makefile
# run `man cc`
